apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: saver
  name: saver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saver
  ports:
    - port: 443
      targetPort: 8080
